// database/seedDB/seedCourses.ts

import Course from '../models/Course';

const seedCourse = async () => {
  await Course.bulkCreate([
    {
      course_code: 'WEB222',
      course_detail_id: 1,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'WEB222',
      course_detail_id: 1,
      course_term_id: 2,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'WEB222',
      course_detail_id: 2,
      course_term_id: 2,
      course_section: 'NBB',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'PRJ666',
      course_detail_id: 3,
      course_term_id: 3,
      course_section: 'NZA',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'PRJ666',
      course_detail_id: 2,
      course_term_id: 2,
      course_section: 'NBB',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'DBS301',
      course_detail_id: 4,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'DBS301',
      course_detail_id: 4,
      course_term_id: 2,
      course_section: 'NAA',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'OOP345',
      course_detail_id: 2,
      course_term_id: 1,
      course_section: 'NCC',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'OOP345',
      course_detail_id: 3,
      course_term_id: 2,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'IPC144',
      course_detail_id: 4,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'IPC144',
      course_detail_id: 2,
      course_term_id: 2,
      course_section: 'NBB',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'JAV210',
      course_detail_id: 2,
      course_term_id: 3,
      course_section: 'NCC',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'JAV210',
      course_detail_id: 3,
      course_term_id: 2,
      course_section: 'NBB',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'CPS511',
      course_detail_id: 3,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'CPS511',
      course_detail_id: 1,
      course_term_id: 2,
      course_section: 'NAA',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'DSA555',
      course_detail_id: 2,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'DSA555',
      course_detail_id: 3,
      course_term_id: 2,
      course_section: 'NBB',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'AI101',
      course_detail_id: 2,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'AI101',
      course_detail_id: 1,
      course_term_id: 3,
      course_section: 'NZZ',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'ML400',
      course_detail_id: 1,
      course_term_id: 1,
      course_section: 'NBB',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'ML400',
      course_detail_id: 1,
      course_term_id: 2,
      course_section: 'NCC',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'SQA101',
      course_detail_id: 2,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'SQA101',
      course_detail_id: 1,
      course_term_id: 3,
      course_section: 'NZZ',
      course_delivery_format_id: 3,
    },
    {
      course_code: 'IOT303',
      course_detail_id: 3,
      course_term_id: 2,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'IOT303',
      course_detail_id: 1,
      course_term_id: 3,
      course_section: 'NBB',
      course_delivery_format_id: 2,
    },
    {
      course_code: 'BIO101',
      course_detail_id: 2,
      course_term_id: 1,
      course_section: 'NAA',
      course_delivery_format_id: 1,
    },
    {
      course_code: 'BIO101',
      course_detail_id: 4,
      course_term_id: 3,
      course_section: 'NCC',
      course_delivery_format_id: 3,
    },
  ]);
};

export { seedCourse };
