-- Drop tables if they exist to start fresh
DROP TABLE IF EXISTS review_answers CASCADE;
DROP TABLE IF EXISTS review_questions CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS review_types CASCADE;
DROP TABLE IF EXISTS review_statuses CASCADE;
DROP TABLE IF EXISTS course_delivery_formats CASCADE;
DROP TABLE IF EXISTS course_terms CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS course_details CASCADE;
DROP TABLE IF EXISTS professors CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS professor_courses CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS review_type CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS admin_action_types CASCADE;
DROP TABLE IF EXISTS admin_actions CASCADE;
DROP TABLE IF EXISTS review_history CASCADE;
DROP TABLE IF EXISTS review_policy_violation_logs CASCADE;

